import { Metadata } from "next";

interface Props {
    children: React.ReactNode;
}
export const metadata : Metadata = {
    title: "Login or Register",
    description: "Generated by create next app",
}
export default function Layout({children} : Props) {
    return (
        <>
        {children}
        </>
    )
}